export const ADD_ORDER = 'inc/order'
export const REMOVE_ORDER = 'remove/order'
export const FETCH_ORDERS = 'fetch/orders'
export const LOAD_ORDERS = 'loading/orders'
export const REJECT_ORDERS = 'reject/orders'
